Descriptor download errors accidently suppressed
Oops, forgot that __iter__() suppressed errors. This has caused download errors
to report an unhelpful...

  ERROR: Unable to retrieve the vote from dannenberg
  (http://193.23.244.244:80/tor/status-vote/current/authority): list index out
  of range