Error due to recent BadExit improvement
Pretty simple error that's broken a couple runs so far...

  Traceback (most recent call last):
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 813, in <module>
      main()
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 245, in main
      issues += run_checks(consensuses, votes)
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 333, in run_checks
      issues = checker(latest_consensus, consensuses, votes)
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 680, in bad_exits_in_sync
      desc = votes[with_flag[0]].routers[fingerprint]
  TypeError: 'set' object does not support indexing