Surface errors when health check fails
Oops, since we iterate it suppresses errors resulting in a pretty unhelpful
notice...

  Traceback (most recent call last):
    File "/srv/doctor.torproject.org/doctor/relay_check.py", line 63, in <module>
      main()
    File "/srv/doctor.torproject.org/doctor/relay_check.py", line 32, in main
      ))[0]
  IndexError: list index out of range