Function to log stem debug logs
We're getting a stacktrace that indicates a stem bug...

Traceback (most recent call last):
  File "/home/atagar/Desktop/tor/tor-utils/descriptor_checker.py", line 90, in <module>
    main()
  File "/home/atagar/Desktop/tor/tor-utils/descriptor_checker.py", line 52, in main
    log.debug("  %i descriptors retrieved from %s in %0.2fs" % (count, query.download_url, query.runtime))
TypeError: float argument required, not NoneType

We'll frequently be wanting stem debug logs so adding a function to get them.
Actually, we kinda lucked out since my first run after adding this experienced
the issue. Here's the corresponding stem logs...

07/30/2013 10:14:25 [TRACE] Descriptors retrieved from 'http://171.25.193.9:443/tor/server/all.z' in 19.21s
07/30/2013 10:15:07 [DEBUG] Unable to download descriptors from 'http://154.35.32.5:80/tor/extra/all.z' (2 retries remaining): Error -5 while decompressing data: incomplete or truncated stream
07/30/2013 10:15:40 [DEBUG] Unable to download descriptors from 'http://212.112.245.170:80/tor/extra/all.z' (1 retries remaining): Error -5 while decompressing data: incomplete or truncated stream
07/30/2013 10:16:13 [DEBUG] Unable to download descriptors from 'http://212.112.245.170:80/tor/extra/all.z': Error -5 while decompressing data: incomplete or truncated stream

So... guess the compression issue isn't as solved as I thought. This isn't
gonna be fun to troubleshoot...