Errors due to the recent is_bandwidth_authority attribute change
Our 'authority' keys are strings, not DirectoryAuthority instances...

  Traceback (most recent call last):
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 754, in <module>
      main()
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 238, in main
      issues += run_checks(consensuses, votes)
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 329, in run_checks
      issues = checker(latest_consensus, consensuses, votes)
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 541, in voting_bandwidth_scanners
      if authority.is_bandwidth_authority and not contains_measured_bandwidth:
  AttributeError: 'str' object has no attribute 'is_bandwidth_authority'