Avoid crashing when a vote is missing
Addressing a simple stacktrace I see on occasion...

  Traceback (most recent call last):
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 885, in <module>
      main()
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 244, in main
      issues += run_checks(consensuses, votes)
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 336, in run_checks
      issues = checker(latest_consensus, consensuses, votes)
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 790, in shared_random_commit_partitioning
      if commitment.commit != self_commitments[commitment.identity]:
  KeyError: u'D586D18309DED4CD6D57C18FDB97EFA96D330566'