Fix fallback irc notifications
Correcting a regression with the earlier change...

  Traceback (most recent call last):
    File "/srv/doctor.torproject.org/doctor/fallback_directories.py", line 92, in <module>
      main()
    File "/srv/doctor.torproject.org/doctor/fallback_directories.py", line 87, in main
      util.send('Announce or', body = body, to = ['tor-misc@commit.noreply.org'])
  NameError: global name 'body' is not defined