Stacktrace when all descriptors are unavalable or malformed
Just addressing an interesting edge case that's currently cropping up because the consensus is invalid.

  Traceback (most recent call last):
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 802, in <module>
      main()
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 239, in main
      consensuses, consensus_fetching_issues = get_consensuses()
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 755, in get_consensuses
      return _get_documents('consensus', '/tor/status-vote/current/consensus.z')
    File "/srv/doctor.torproject.org/doctor/consensus_health_checker.py", line 790, in _get_documents
      median_time = sorted(times_taken.values())[len(times_taken) / 2]
  IndexError: list index out of range